name: Commit Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commit-validation:
    name: Commit Validation
    runs-on: ${{ contains(github.server_url, 'github.com') && 'ubuntu-latest' || fromJSON('["self-hosted"]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate current commit (last commit)
        if: ${{ github.event_name == 'push' }}
        run: npx commitlint --last --verbose

      - name: Validate PR title
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose
