name: REUSE Compliance Check

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  check-reuse-compliance:
    name: REUSE Compliance Check
    runs-on: ${{ contains(github.server_url, 'github.com') && 'ubuntu-latest' || fromJSON('["self-hosted"]') }}
    steps:
    - uses: actions/checkout@v6

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v6.0.0
